spring:
  datasource:
  generate-unique-name: false
  name: tacocloud
  url : jdbc:h2:mem:tacocloud

  h2:
      console:
        path: /h2
  jpa:
    show-sql: true


server:
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        security: DEBUG